### ISSUE TITLE
Bug with multiple libraries

### ISSUE THREAD

**Issue by daniel78110** [broadinstitute/chronos#1]
Hello,

I was taking chronos for a spin (on Broad Achilles data). It worked on 1 set of experiments, but hit an error when running on multiple libraries:

```
  File "chronos-wrapper.py", line 82, in <module>
    main()
  File "chronos-wrapper.py", line 75, in main
    model = chronos.Chronos(readcounts = readcounts, sequence_map = sequence_maps, guide_gene_map = guide_gene_maps)
  File "/opt/conda/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 509, in __init__
  File "/opt/conda/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 1105, in smart_initialize
  File "/opt/conda/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 1337, in cell_efficacy
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['143B', '21NT', '2313287', '253J', '42MGBA', '5637', '59M', '639V', '647V', '697', '769P', '8305C', '8MGBA', '93T449', '94T778', '9505BIK', '95T1000', 'A2058', 'A253', 'A375', 'A375SKINCJ1', 'A375SKINCJ2', 'A375SKINCJ3', 'A388', 'A3KAW', 'A427', 'A431', 'A549', 'A673', 'ABC1', 'ACCMESO1', 'AGS', 'AML193', 'AMO1', 'ANGMCSS', 'ASH3', 'ASPC1', 'BC3C', 'BFTC905', 'BFTC909', 'BHY', 'BICR16', 'BICR22', 'BICR31', 'BICR56', 'BICR6', 'BICR78'] not in index"
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py:1278: The name tf.delete_session_tensor is deprecated. Please use tf.compat.v1.delete_session_tensor instead.
```

It seems at a glance that it is confused by the fact that the cell_line_names are not the same across libraries.... is there an underlying assumption about this?

Cheers,

Daniel

**Comment by joshdempster** [comment]
Hi Daniel,

Thanks for checking it out. This appears to be a manifestation of a breaking change introduced in pandas in how indexing behaves when keys are missing. I have an updated version of Chronos in the works which should fix this.

**Comment by daniel78110** [comment]
Ace, thanks for the fast response!

**Comment by joshdempster** [comment]
Hi Daniel,

I'm not sure if the latest push will fix your issue. Can you give it a shot?

**Comment by daniel78110** [comment]
Hello @joshdempster ,

Apologies for the month long tardiness. 

It seems to have gone farther down the route, but now I have a mysterious kill signal:

```

Connecting graph nodes in model

building effective days
built effective days, shapes {'3': [20, 21204], 'SCORE': [28, 21204]}

building gene effect growth graph nodes
built gene effect growth graph nodes, shapes {'3': [20, 21204], 'SCORE': [20, 21204]}

building combined efficacy
built combined efficacy, shape {'3': [20, 74344], 'SCORE': [20, 100934]}
built expanded combined efficacy, shapes {'3': [20, 74344], 'SCORE': [28, 100934]}

building growth estimates of edited cells and overall estimates of fold change in guide abundance
built growth and change

building unnormalized estimates of final abundance
built unnormalized abundance

building normalized estimates of final abundance
built normalized abundance


Building all costs

assembling guide efficacy regularization
Killed
```

Does this make any sense to you?

Cheers,

Daniel

**Comment by joshdempster** [comment]
Hi Daniel,

That's not something we've experienced in our environments, I suspect a
version problem. We've switched the master to be TF2+ compatible. Could you
tell me your tensorflow, numpy, and pandas versions? Also, it looks like
there should be some additional lines to the traceback?

Best,

Josh

**Comment by daniel78110** [comment]
Hello Josh,

Thanks for the info! My config is:
```
conda install python=3.7 tensorflow=1.15 numpy=1.20.3 pandas=1.3.1 patsy=0.5.1 h5py=3.2.1
```

As for the traceback, I'm afraid that's all I have. Note that I have a little wrapper script to run Chronos. To give you more context below are the lines before the traceback:
```

Connecting graph nodes in model

building effective days
built effective days, shapes {'SCORE': [28, 21204], '3': [20, 21204]}

building gene effect growth graph nodes
built gene effect growth graph nodes, shapes {'SCORE': [20, 21204], '3': [20, 21204]}

building combined efficacy
built combined efficacy, shape {'SCORE': [20, 100934], '3': [20, 74344]}
built expanded combined efficacy, shapes {'SCORE': [28, 100934], '3': [20, 74344]}

building growth estimates of edited cells and overall estimates of fold change in guide abundance
built growth and change

building unnormalized estimates of final abundance
built unnormalized abundance

building normalized estimates of final abundance
built normalized abundance


Building all costs

assembling guide efficacy regularization
building smoothed regularization
Traceback (most recent call last):
  File "../chronos-wrapper.py", line 86, in <module>
    main()
  File "../chronos-wrapper.py", line 78, in main
    model = chronos.Chronos(readcounts=readcounts, sequence_map=sequence_maps, guide_gene_map=guide_gene_maps)
  File "/opt/conda/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 463, in __init__
  File "/opt/conda/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 1023, in _get_smoothed_ge_regularization
TypeError: convolution() missing 1 required positional argument: 'filter'
```

Last but not least, I should have asked earlier, but under what license is Chronos?

Cheers,

Daniel

**Comment by daniel78110** [comment]
PS: Upgrading to TF 2.4.1 I now get an even more confusing message:

```
building late observed timepoints
2021-09-21 09:12:33.408509: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-09-21 09:12:33.439742: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 1996800000 Hz
	built normalized timepoints for SCORE with shape (28, 100934) (replicates X guides)
	built normalized timepoints for 3 with shape (20, 74344) (replicates X guides)

building initial reads


Building variables

building initial reads estimate
Traceback (most recent call last):
  File "/data/../chronos-wrapper.py", line 86, in <module>
    main()
  File "/data/../chronos-wrapper.py", line 78, in main
    model = chronos.Chronos(readcounts=readcounts, sequence_map=sequence_maps, guide_gene_map=guide_gene_maps)
  File "/opt/conda/lib/python3.9/site-packages/chronos-0.1.1-py3.9.egg/chronos/model.py", line 427, in __init__
  File "/opt/conda/lib/python3.9/site-packages/chronos-0.1.1-py3.9.egg/chronos/model.py", line 776, in _get_initial_tf_variables
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py", line 4095, in unsorted_segment_mean
    N = _unsorted_segment_N(data, segment_ids, num_segments)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py", line 4046, in _unsorted_segment_N
    array_ops.ones([array_ops.rank(data)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 3120, in ones
    output = _constant_if_small(one, shape, dtype, name)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/opt/conda/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/opt/conda/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 852, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (grouped_diff_SCORE/sub:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

**Comment by mmaalvarez** [comment]
Hi, I just downloaded and installed chronos, and running the example code from the vignette, I am also stuck at the 
```
model = chronos.Chronos(
    readcounts={"avana": readcounts},
    sequence_map={"avana": sequence_map},
    guide_gene_map={"avana": guide_map}
)
```
step, with this error:
```
Traceback (most recent call last):
  File "chronos_workflow.py", line 55, in <module>
    guide_gene_map={"avana": guide_map}
  File "/home/user/.conda/envs/chronos/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 463, in __init__
  File "/home/user/.conda/envs/chronos/lib/python3.7/site-packages/chronos-0.1.1-py3.7.egg/chronos/model.py", line 1023, in _get_smoothed_ge_regularization
TypeError: convolution() missing 1 required positional argument: 'filter'
```

**Comment by yh154** [comment]
I also got the same error by following the vignette from chronos. Will appreciate very much for some insights: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/data/abl/home/haoy04/Poirier/chronos/chronos/model.py", line 463, in __init__
    self._smoothed_presum = self._get_smoothed_ge_regularization(self.v_mean_effect, self._true_residue, kernel_width, dtype)
  File "/gpfs/data/abl/home/haoy04/Poirier/chronos/chronos/model.py", line 1023, in _get_smoothed_ge_regularization
    _residue_smoothed = tf.nn.convolution(input=_residue_sorted, filters=_kernel, padding='SAME')
TypeError: convolution() missing 1 required positional argument: 'filter'

**Comment by joshdempster** [comment]
Hi both, sorry for the long delay. I've been out on family leave since September. It's clear that the error is a tensorflow version problem. Annoyingly, it's switched from filter to filters as the keyword in a function. Upgrading to TF 2.x will solve that problem at least. I will change the installation requirements to force the tensorflow upgrade. Daniel, your second error will require more investigation on my end.

**Comment by joshdempster** [comment]
@daniel78110 I have upgraded my environment to the latest versions of the relevant packages and still can't produce this error. Is this happening with just the vignette? If not, I suspect a file format issue somewhere that's not being caught by the default checks.

**Comment by joshdempster** [comment]
Setup.py updated with package version requirements which should resolve the convolution syntax error.

**Comment by daniel78110** [comment]
Thanks @joshdempster I'll give it a spin this week or next!

**Comment by mmaalvarez** [comment]
Thanks @joshdempster
With tensorflow 2.7 it succesfully trains the example model, but now it fails at the scaling step:

`Traceback (most recent call last):
  File "chronos_workflow.py", line 88, in <module>
    sns.kdeplot(gene_effects[nonessentials].stack(), label="Nonessentials", gridsize=1000)
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/seaborn/distributions.py", line 1778, in kdeplot
    **plot_kws,
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/seaborn/distributions.py", line 934, in plot_univariate_density
    warn_singular,
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/seaborn/distributions.py", line 303, in _compute_univariate_density
    for sub_vars, sub_data in self.iter_data("hue", from_comp_data=True):
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/seaborn/_core.py", line 983, in iter_data
    data = self.comp_data
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/seaborn/_core.py", line 1057, in comp_data
    comp_col.loc[orig.index] = pd.to_numeric(axis.convert_units(orig))
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/indexing.py", line 723, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/indexing.py", line 1732, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/indexing.py", line 1959, in _setitem_single_block
    value = self._align_series(indexer, Series(value))
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/indexing.py", line 2096, in _align_series
    ser = ser.reindex(obj.axes[0][indexer[0]], copy=True)._values
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/series.py", line 4580, in reindex
    return super().reindex(index=index, **kwargs)
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/generic.py", line 4819, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/generic.py", line 4835, in _reindex_axes
    labels, level=level, limit=limit, tolerance=tolerance, method=method
  File "/home/malvarez/.conda/envs/chronos/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 2524, in reindex
    raise ValueError("cannot handle a non-unique multi-index!")
ValueError: cannot handle a non-unique multi-index!
`

**Comment by joshdempster** [comment]
This looks to me like a seaborn compatibility issue with the latest pandas. You can comment out the seaborn plot commands in that cell.

**Comment by mmaalvarez** [comment]
thanks, commenting out the seaborn plot commands worked
